### ISSUE TITLE
Exit Code 128 during Git Clone

### ISSUE THREAD

**Issue by slinkardbrandon** [garden-io/update-homebrew-action#11]
Hello! I started playing around with this repo and ran into an issue with my implementation [in this action run](https://github.com/4rbor/tq/runs/1277609957?check_suite_focus=true). I was mostly curious if anyone had seen this issue before when implementing this action. I have `AUTH_TOKEN` set in my repo secrets and it has sufficient access, yet the build still continues to fail when the action runs. Any ideas?

**Actions File**
```
name: Update Homebrew Formula

on:
  push:
    branches:
      - "main"

jobs:
  homebrew-release:
    runs-on: macos-latest
    steps:
      - name: Release Homebrew Formula
        uses: garden-io/update-homebrew-action@v1
        with:
          packageName: "tq"
          templatePath: "support/homebrew-formula.rb"
          tapRepo: "4rbor/homebrew-tq"
          srcRepo: "4rbor/tq"
          authToken: ${{ secrets.AUTH_TOKEN }}
```

**Action Logs**
```
Run garden-io/update-homebrew-action@v1
  with:
    packageName: tq
    templatePath: support/homebrew-formula.rb
    tapRepo: 4rbor/homebrew-tq
    srcRepo: 4rbor/tq
    authToken: ***
Pulling the homebrew repo
Error: Command failed with exit code 128 (Unknown system error -128): git clone git@github.com:4rbor/homebrew-tq.git
```
